#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: 
  - Visual Studio 2017
  - Ubuntu
  
environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true

#---------------------------------#
#  Build Script                   #
#---------------------------------#
for:
-
  matrix:
    only:
      - image: Visual Studio 2017
    
  build_script:
    - ps: .\build.ps1 --target="AppVeyor-With-Integration-Tests" --verbosity="Diagnostic"
-
  matrix:
    only:
      - image: Ubuntu
    
  build_script:
    - sh: chmod +x ./build.sh
    - sh: ./build.sh --target="AppVeyor-With-Integration-Tests" --verbosity="Diagnostic"

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1